# Generated by Django 2.2 on 2022-04-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='place',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Полное описание места'),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.CharField(blank=True, max_length=350, verbose_name='Краткое описание места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Название места'),
        ),
    ]
