# Generated by Django 2.2 on 2022-04-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.ImageField(null=True, upload_to='', verbose_name='Номер картинки'),
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='places.Place', verbose_name='К какому месту относится'),
        ),
    ]
