# Generated by Django 2.2 on 2022-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20220402_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(blank=True, max_length=70, verbose_name='Название места'),
        ),
    ]
