# Generated by Django 4.0.3 on 2022-04-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_options_alter_image_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
