# Generated by Django 4.0.3 on 2022-04-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер картинки'),
        ),
    ]
