# Generated by Django 3.1 on 2022-04-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20220409_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='ID места'),
        ),
    ]
