# Generated by Django 3.1 on 2022-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20220409_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер картинки'),
        ),
    ]
