# Generated by Django 3.1 on 2022-04-09 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20220409_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='places.place', verbose_name='К какому месту относится'),
        ),
    ]
